### ISSUE TITLE
Добавить отдачу кнопкам +,-

### ISSUE THREAD

**Issue by baitun** [laapl/desktop#2]
Сейчас кнопки никак не проявляют себя при наведении и при нажатии. Да я знаю, что в левом верхнем углу карточки изменяется цифра с количеством товара в корзине, но все-равно когда кликаешь на кнопку и она никак не реагирует, возникает ощущение что она не работает.
![update3](https://user-images.githubusercontent.com/5827605/51709632-e22c9580-2061-11e9-9583-91f0bfd44f41.gif)
Нужно как то показывать, что кнопка была нажата. Ну и при наведении тоже не помешало бы ее как-нибудь выделять.

**Comment by BorisHasikov** [comment]
Визуализирую нажатие.
